### ISSUE TITLE
Links to Gmane broken.

### ISSUE THREAD

**Issue by GadgetSteve** [wxWidgets/website#32]
As Gmane is dead it looks like the  links should simply be removed.

**Comment by GadgetSteve** [comment]
The attached is a zip of a patch that removes the links to gmane from the mailing lists page and marks as a dead link the one occurrence in gsoc/projects - other references were found but they are all in historic blog entries which I felt shouldn't be touched.
[issue32.zip](https://github.com/wxWidgets/website/files/2765432/issue32.zip)

**Comment by tierra** [comment]
Applied in 45f825fd5e562d988ebdf5ff683737faac9e8ed8 with minor changes, thanks.
