### ISSUE TITLE
Certificate for wxpython.org expired

### ISSUE THREAD

**Issue by antonio-fr** [wxWidgets/website#52]
Just to let you know that the HTTPS certificate signed by LetsEncrypt for wxpython.org expired on Thu, 04 Mar 2021 00:04:28 GMT.

**Comment by vadz** [comment]
Thanks for reporting this, but this repository only contains www.wxwidgets.org web site, so I can't do anything about it.

@RobinD42 are you aware of the problem?

**Comment by RobinD42** [comment]
I think @tierra is the one to ask about it.

**Comment by RobinD42** [comment]
Looks like there may be an issue with LetsEncrypt. One of my domains didn't auto renew either.

**Comment by tierra** [comment]
Looks like you got it figured out.
