### ISSUE TITLE
Publish workflow got broken

### ISSUE THREAD

**Issue by vadz** [wxWidgets/website#64]
For some reason publish workflow doesn't run any more, see e.g. [this run](https://github.com/wxWidgets/website/runs/4385760812?check_suite_focus=true). The weird thing is that this error appeared ~12 hours ago for the first time, but there was one [successful run](https://github.com/wxWidgets/website/actions/runs/1526011167) since then, while all the other have failed.

AFAICS the error happens because something (what?) requires C++14 compiler now (`std::remove_cv_t` is C++14 only), but we must not be using one. The simplest fix would be pin this something, whatever it is, to an earlier version. Alternatively we can try running the workflow on Ubuntu 20.04.

@tierra Any hints would be welcome, I've never used yarn in my life so I have no idea what it does nor how to tell it to use an older version of node-sass (?). TIA!

**Comment by vadz** [comment]
Switching to 20.04 didn't help, but looking closer at the log, it's calling the compiler with `-std=gnu++14 -std=c++0x` options, i.e. it explicitly disables the use of C++14 with the latter choice of C++11. Unfortunately I have no idea where does this `c++0x` come from nor how to get rid of it...

**Comment by tierra** [comment]
That's really weird. We do already lock all NPM packages in [yarn.lock](https://github.com/wxWidgets/website/blob/master/yarn.lock#L1250-L1253). I'll check this out later tonight.

**Comment by vadz** [comment]
I've fixed this by upgrading to node-sass 6.0.1 as I couldn't find a way to use a previous Node version and only node-sass 6 supports Node 16.

This did fix the build, I just hope this didn't break any functionality. The web site looks fine at first glance, but I have no idea what could have changed in node-sass since the v4 that we previously used. But I've also seen that it has been deprecated now, so hopefully they didn't change it in a backwards incompatible way before deprecating it. Hopefully...
