### ISSUE TITLE
Screenshot images are inverted in dark mode

### ISSUE THREAD

**Issue by willco007** [wxWidgets/website#79]
The new doxygen dark theme is applying a hue invert style to screenshot images which causes them to be incorrectly inverted in dark mode.

The offending CSS is in `html.dark-mode` and `@media (prefers-color-scheme: dark)` which does:

```filter: hue-rotate(180deg) invert();```

you can see this being incorrectly applied to the button examples here:

https://docs.wxwidgets.org/3.2/classwx_button.html

**Comment by vadz** [comment]
We probably need to define some class that could be used to prevent this from happening and use it for the images used in the screenshots? Any help from more CSS-minded folks would be welcome.

**Comment by tierra** [comment]
I've applied a fix for this in https://github.com/wxWidgets/wxWidgets/commit/6a10064d24ff27913f289009c12623bb03aed6b3

**Comment by tierra** [comment]
It might take some time to update on the online docs by the way, since the stylesheets are cached aggressively.

**Comment by tierra** [comment]
Should I keep this open assuming it should be backported to 3.2?

**Comment by vadz** [comment]
Thanks a lot for fixing this! I'll include it in 3.2.1.
