### ISSUE TITLE
Dead link (anchor #twostep_ctor) within Coding Guidelines

### ISSUE THREAD

**Issue by Wolf-SO** [wxWidgets/website#88]
The last sentence in the section [*Don't use exceptions*](https://wxwidgets.org/develop/coding-guidelines/#no_exceptions) seems to refer to details on the subject of two-step construction:

> The special case of constructors, which have no return value, is typically handled by providing an IsOk() method indicating whether the object was constructed successfully and, for all wxWindow-derived classes, also by using [two-step construction](https://wxwidgets.org/develop/coding-guidelines/#twostep_ctor).

But there is no section about it on this page. (At least none that I've been able to find so far).

**Comment by vadz** [comment]
I've fixed this in the most expedient way possible, thanks.
