### ISSUE TITLE
Email broken for core maintainer Paul

### ISSUE THREAD

**Issue by seanbudd** [wxWidgets/website#92]
Paul's email on this page appears dead, after getting an auto reject response from contacting him: https://www.wxwidgets.org/about/team/

**Comment by vadz** [comment]
@paulcor Could you please update this (or remove it if you don't want to be contacted by email, of course).

@seanbudd I did get your email but won't be able to answer it until tomorrow, sorry.

**Comment by seanbudd** [comment]
No rush - I figured you may need to discuss that internally first
