### ISSUE TITLE
Warn when viewing outdated docs

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/website#93]
When googling for wxWidgets class to see its docs, usually the top result is for v3.0 or something, i.e., severally outdated. 

I know nothing about webservers but I wonder if there is not some easily done and not performance taxing magic (htaccess etc.) that could inject a warning to html docs that are not for the master or the stable version, i.e., something like [boost](https://www.boost.org/doc/libs/1_75_0/libs/outcome/doc/html/index.html) or [CMake](https://cmake.org/cmake/help/v3.17/variable/CMAKE_CXX_STANDARD.html) docs do.

**Comment by tierra** [comment]
I've updated `robots.txt` to ignore 3.0 docs in favor of only indexing 3.2 docs. This is how we've generally handled older versions, just didn't get around to adding 3.0 when 3.2 was pushed out.

It'll be a while before that really takes affect, but it should help in the next couple weeks.
