### ISSUE TITLE
Screenshots in blog post Great Grid Updates are not displayed

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/website#96]
Screenshots in blog post _Great Grid Upgrades_ added in https://github.com/wxWidgets/website/commit/cf6b6fde308d09ba7e8e5e73d4f2f07a261a13c0 are not displayed: https://wxwidgets.org/blog/2024/06/great-grid-upgrades/

The images links are insanely long github URLs, probably copied from the code PRs: Either they are invalid in the blog post (they do not work when used as an address in a browser) or too long to be handled properly by the blog system.

Perhaps it would be better to upload the images along the blog text at wxWidgets website, as it was done e.g. in https://github.com/wxWidgets/website/commit/e34ef072be6e7a4ab474b9330f59a4861fc2e5c9.

@AliKet already commented this on the blog entry itself, but perhaps it was missed.

BTW, I believe it would be for the best if new blog posts were announced in wx-dev and/or wx-users: It is very easy to miss them, as they do not appear on the wxWidgets homepage either. Both groups are rather low-traffic and new blog posts are rare...

**Comment by vadz** [comment]
Thanks for opening this, I've indeed missed the comment on the blog itself (I have no idea if I can set up some kind of notification for them) and I've copied the images now, but I still wonder if there is a better way to handle this than to do it like this...

**Comment by tierra** [comment]
> I have no idea if I can set up some kind of notification for them

I do have these setup myself (though probably enabled by default since I set up the system), but actually just noticed that it landed in my spam box (hopefully fixed now).

Anyway, I'm sure anyone is able to subscribe to all comments on the site through the Disqus dashboard, certainly at least you can as a moderator.

**Comment by vadz** [comment]
Thanks, I didn't know about the existence of such an option before but I've enabled emails for all comments site-wide now.
